apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: incoming
spec:
  interceptors:
    - cel:
        filter: "header.match('X-GitHub-Event', 'push')"
  bindings:
  - ref: incoming-binding
  template:
    ref: incoming-template
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: outgoing
spec:
  interceptors:
    - cel:
        filter: "body.token == 'vrn1jwx4a9h'"
  bindings:
  - ref: outgoing-binding
  template:
    ref: outgoing-template
