apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: trigger
spec:
  interceptors:
    - cel:
        filter: "header.match('X-GitHub-Event', 'push')"
  bindings:
  - ref: pipeline-binding
  template:
    ref: pipeline-template
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: outgoing
spec:
  interceptors:
    - cel:
        filter: "body.token == 'vrn1jwx4a9h'"
  bindings:
  - ref: contenttype-binding
  template:
    ref: outgoing-template
